### ISSUE TITLE
시간 비교 함수 

### ISSUE THREAD

**Issue by gimyojun** [wls0210/Assignment2#14]
void timecmp(void)
111 {
112    int hour1,min1;
113    int hour2,min2;
114    hour1=time1->tm_hour;
115    min1=time1->tm_min;
116    hour2=time2->tm_hour;
117    min2=time2->tm_min;
118    printf("time compare\n");
119    if(hour1==hour2){
120       if(min1==min2)
121          printf("same time\n");
122       else if(min1>min2)
123          printf("text1 is early\n");
124       else
125          printf("text2 is early\n");
126 
127    }
128    else if(hour1>hour2)
129       printf("text1 is early\n");
130    else
131       printf("text2 is early\n");
132 }
이렇게 작성 해봤습니다

**Comment by wls0210** [comment]
문제는 없어 보입니다.

**Comment by wls0210** [comment]
다시보니 time1과 time2가 참조하는 변수가 존재 하지 않아서 문제가 있을 것 같네요... 제 부분 수정해서 올리겠습니다.

**Comment by gimyojun** [comment]
수정해서 올리겠습니다.

**Comment by wls0210** [comment]
수정 완료했습니다.
