### ISSUE TITLE
time1, time2에 관한 문제..

### ISSUE THREAD

**Issue by wls0210** [wls0210/Assignment2#4]
두 변수는 전역변수로써 tm* 형으로 선언되어 있기 때문에 함수내에서 시간을 계산해서 주소값을 저장하는 것은 의미가 없는것 같은데 동적할당으로 변수를 생성해서 저장을 하는게 효율적일까요 아니면 함수를 호출할 때마다 filestat변수를 활용해서 계산하는것이 효율적일까요?

**Comment by gimyojun** [comment]
동적할당하는 방법이 적합할거같습니다

**Comment by wls0210** [comment]
넵. 수정해서 올리겠습니다.

**Comment by gimyojun** [comment]
네. 뒷 부분 수정해서 올리겠습니다.
